@startuml

!define BITCOIN_ICON_URL bitcoin.png
!define MONERO_ICON_URL monero.png
!define TOR_ICON_URL tor.svg

component "Taker (Buyer / User)" as Taker {
    component "<img:gui.png{scale=0.1}>" as CLI
    component [Bitcoin Wallet] as CliBitWal
    component [Monero Wallet] as CliMonWal
    component "<img:BITCOIN_ICON_URL{scale=0.01}> Bitcoin" as TakerBitcoinBC
    component "<img:MONERO_ICON_URL{scale=0.01}> Monero" as TakerMoneroBC
}

cloud "<img:TOR_ICON_URL{scale=0.05}> Tor Network" as TorNetwork {
    component "Taker" as TakerTor
    component "Maker\n(Onion Service)" as MakerTor
    component "Rendezvous Point" as RendezvousPoint
    TakerTor <--> MakerTor: Custom Trade Protocol\n(Signaturen, etc.)
    TakerTor <--> RendezvousPoint: Discover Makers
    RendezvousPoint <--> MakerTor: Announce Self
}

component "Maker (Seller)" as Maker {
    component [ASB] as ASB
    component [Bitcoin Wallet] as AsbBitWal
    component [Monero Wallet] as AsbMonWal
    component "<img:BITCOIN_ICON_URL{scale=0.01}> Bitcoin" as MakerBitcoinBC
    component "<img:MONERO_ICON_URL{scale=0.01}> Monero" as MakerMoneroBC
}


CliBitWal -- TakerBitcoinBC
CliMonWal -- TakerMoneroBC
AsbBitWal -- MakerBitcoinBC
AsbMonWal -- MakerMoneroBC

Taker .. TorNetwork
TorNetwork .. Maker

@enduml
