@startuml

package "Taker (Buyer / User)" {
    component [Monero Wallet RPC\n(auto installed)] as CliMonRpc
    () RPC as MonRpcCli
    component "swap" {
        component "<img:gui.png{scale=0.2}>" as CLI
        component [Bitcoin Wallet] as CliBitWal
    }
    CliMonRpc - MonRpcCli
    CLI - CliBitWal
    MonRpcCli - CLI
}

package "Monero Blockchain" {
    component "monerod" as Monerod
}

package "Bitcoin Blockchain" {
    component "Electrum Server" as Electrum
    component "bitcoind" as Bitcoind
    () "RPC" as BitRPC
    BitRPC -- Electrum
    Electrum - Bitcoind
}

package "Maker (Seller)" {
    component [Monero Wallet RPC] as AsbMonRpc
    () RPC as MonRpcAsb
    component "asb" {
        component [ASB] as ASB
        component [Bitcoin Wallet] as AsbBitWal
    }
    AsbMonRpc - MonRpcAsb

    component "monerod" as AsbMonerod
    component "Electrum Server" as AsbElectrum
    component "bitcoind" as AsbBitcoind

    AsbMonRpc -- AsbMonerod

    () "RPC" as AsbBitRPC

    AsbBitWal -- AsbBitRPC
    AsbBitRPC -- AsbElectrum
    AsbElectrum - AsbBitcoind

    ASB - AsbBitWal
    ASB -- MonRpcAsb
}

package "Public Price Server" {
    component [CEX Price Ticker] as CEX
    () "websocket" as Ticker
    Ticker - CEX
    Ticker -- ASB
}

CliBitWal -- BitRPC
CliMonRpc -- Monerod

!define ICONURL https://www.torproject.org/static/images/tor-logo/onion.svg

cloud "<size:20>The Onion Network (Tor)</size>" as TorNetwork #7D4698 {
    () "Custom Network Protocol" as Libp2p
}
CLI -- Libp2p
ASB -- Libp2p

footer XMR<>BTC swap CLI & ASB overview\nRendered with PlantUML version %version()
@enduml
